### ISSUE TITLE
Benchmark suite

### ISSUE THREAD

**Issue by jamesli2021** [viterin/vek#1]
I like to propose adding benchmark test files so we can test in our own OS environment and compare to GMP?

**Comment by viterin** [comment]
There's benchmarks for the internal implementation that you can run with `go test -benchmem -timeout 0 -run=^# -bench=. ./internal/...`, I'll need to restructure them so they run against the public API at some point

**Comment by jamesli2021** [comment]
Ran your benchmark on M1 SoC.
```
goos: darwin
goarch: arm64
pkg: github.com/viterin/vek/internal/functions
BenchmarkSumProd/go_sum_f64_10-8         	203653389	         5.636 ns/op	       0 B/op	       0 allocs/op
BenchmarkSumProd/go_sum_f32_10-8         	212780042	         5.631 ns/op	       0 B/op	       0 allocs/op
panic: not implemented

goroutine 11 [running]:
github.com/viterin/vek/internal/functions.Sum_AVX2_F64(...)
	/Users/s/Documents/partial/vek/internal/functions/accel_noasm.go:47
github.com/viterin/vek/internal/functions.BenchmarkSumProd.func3(0x1400013ed80?)
	/Users/s/Documents/partial/vek/internal/functions/aggregates_test.go:67 +0x3c
testing.(*B).runN(0x1400013ed80, 0x1)
	/usr/local/go/src/testing/benchmark.go:193 +0x12c
testing.(*B).run1.func1()
	/usr/local/go/src/testing/benchmark.go:233 +0x50
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:226 +0x90
exit status 2
FAIL	github.com/viterin/vek/internal/functions	3.859s
FAIL
```

**Comment by viterin** [comment]
The benchmarks don't run on mac as the SIMD accelerated code is X86 specific. On macs all `vek` functions fall back to a pure, non-optimized, go version.
